# Generated by Django 3.1.3 on 2023-05-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20230501_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_commnet',
            field=models.IntegerField(default=0),
        ),
    ]
