# Generated by Django 3.1.3 on 2023-05-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_question_answer_commnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_commnet',
            new_name='answer_comment',
        ),
    ]
