# Generated by Django 3.1.3 on 2023-05-22 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0008_auto_20230510_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='voter_commnet', to=settings.AUTH_USER_MODEL),
        ),
    ]
