# Generated by Django 3.1.3 on 2023-05-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_comment_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_counter',
            field=models.IntegerField(default=0),
        ),
    ]
