# Generated by Django 3.1.3 on 2023-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_question_modify_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_counter',
            field=models.IntegerField(default=0),
        ),
    ]
